services:
  - type: web
    name: ethra-backend
    env: python
    rootDirectory: backend
    buildCommand: pip install -r requirements.txt
    startCommand: alembic upgrade head && gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ethra-db
          property: connectionString
      - key: PROJECT_NAME
        value: HRMS Lite

databases:
  - name: ethra-db
    databaseName: hrms_db
    user: hrms_user
